[package]
name = "y"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y"
path = "main.rs"

[features]
unstable-features = [] # for rust-analyzer

# Do not add any dependencies
[target.'cfg(target_os = "linux")'.dependencies]
landlock = "0.4.4"

[profile.dev]
debug = 1
